### ISSUE TITLE
Corrupted/stretched 16-pixel wide tiles in 2bpp mode

### ISSUE THREAD

**Issue by jburks** [fvdhoef/vera-module#17]
Both 16x8 and 16x16 tiles appear stretched and some tiles do not show at all due to invalid address calculation in layer renderer.

E.g. with these five test tile targets:

![image](https://user-images.githubusercontent.com/326088/191173972-547e7489-c641-4bbc-b6d6-d8d2067c80f3.png)

Rendering tile 2 on top of tile 3 comes out as this:

![image](https://user-images.githubusercontent.com/326088/191173828-b67a01a7-7847-4250-b84e-95f6c7a9c494.png)

It is not possible to render tile 3 as its address is always calculated to be in the middle of tile 2.

**Comment by fvdhoef** [comment]
Wow, thanks for all your thorough testing and fixing!
