### ISSUE TITLE
Alpha Channel

### ISSUE THREAD

**Issue by FlightControl-User** [fvdhoef/vera-module#3]
@fvdhoef Heb je ooit de toevoeging van een "alpha channel" in de 2 byte rgb mixer beschouwd? Je hebt 4 bits vrij per rgb palette register.
Het zou mooi zijn om ook transparantie labels te hebben in de vera.

Ik ben Sven Van de Velde op de CX16 portal. Ik woon in Antwerpen. Jij blijkbaar in Revele tegen Turnhout?

**Comment by fvdhoef** [comment]
Hallo Sven, het ontwerp is als zo'n 2.5 jaar geleden bevroren. Dit soort toevoegingen zouden zeker mogelijk zijn. Ik woon inderdaad in Ravels, boven Turnhout.

**Comment by FlightControl-User** [comment]
Interessant. Dus het was niet dat er een bepaalde limiet was bijvoorbeeld qua cpu of geheugen voor die alpha. Geen probleem. Je kaart is erg goed. Het is een erg grote uitdaging om het gelimiteerde geheugen te orchestreren tijdens een 60x per seconde synchrone raster frame interrupt en een volledige game flow te bouwen. Ik ben er nog aan bezig op de CX16. Stap voor stap. Heb reeds erg veel geleerd en voel me terug 16 jaar :)

**Comment by fvdhoef** [comment]
Leuk om te horen. Veel plezier er mee!

**Comment by FlightControl-User** [comment]
Ik weet niet of je tijd hebt om even met David contact op te nemen. Hij heeft je hulp nodig. Heb je zijn laatste Facebook post gezien? Ze zitten in de knoei met de PS/2 poort voor het keyboard. 

Ik citeer:

_We figured we’d talk to the micro-controller via I2C.  Frank was going to get this working for us, but he was having trouble with it, and there hasn’t been any word from him in months._

Ik neem aan dat het geen eenvoudige klus is, maar het is een van de laatste loodjes om de board configuratie af te werken. 

Er zijn honderden geïnteresseerden in het X16 platform. Pls. Ik kan je helpen om kosten te dekken.

**Comment by FlightControl-User** [comment]
Kijk even naar deze thread 🥇 , waarin je vera wordt gedemonstreerd ...

https://www.commanderx16.com/forum/index.php?/topic/2524-equinoxe-game-engine-progress/
