### ISSUE TITLE
Add option to disable PSG/Pal/Sprite in VRAM space

### ISSUE THREAD

**Issue by mist64** [fvdhoef/vera-module#9]
Because the PSG/Pal/Sprite registers overlap with the top 1.5 KB of VRAM, this space is effectively unusable for graphics data. I am suggesting having a bit in `CTRL` turn on and off access to PSG/Pal/Sprite. This way, applications can use all 128 KB of VRAM by turning off this area temporarily.

**Comment by fvdhoef** [comment]
The 1.5KB of VRAM isn't unused, it is used to store a copy of the PSG/PAL/Sprite registers so they can be read back by the application.

**Comment by mist64** [comment]
Oooooh, the VERA docs suggested otherwise. Thanks.
